### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'fnn.bin'

### ISSUE THREAD

**Issue by GeekV5** [YSunLIN/FCM_FNN#2]
When I ran this code, I ran into this problem: The fnn.bin file could not be found. I want to ask you  with the fnn.bin file. 
I have been studying fuzzy cognitive maps recently. Your code is very useful to me , and I want to talk to you about the research knowledge about fuzzy cognitive map.
Thanks!

**Comment by YSunLIN** [comment]
https://github.com/YSunLIN/FCM_FNN/blob/619669f99ddeecb4016dfc89eeb3b8ec9ebea1b7/test_MG.py#L21-L25

You can comment the code from line 21 to line 22 and uncomment line 24. Then you will get my code running correctly.

After first running, the weight of trained FNN will store in `fnn.bin`. And you can restore the training process by using the original code.
